module.exports = {
    User: require("./User.model"),
    Order: require("./Order.model"),
    OrderRequirement: require("./OrderRequirement.model"),
    Cargo: require("./Cargo.model"),
    Route: require("./Route.model"),
    RouteDistance: require("./RouteDistance.model"),
    RouteDuration: require("./RouteDuration.model"),
    Point: require("./Point.model"),
    Location: require("./Location.model"),
    Address: require("./Address.model"),
    OrderStatus: require("./enum/OrderStatus.enum"),
    CargoType: require("./enum/CargoType.enum"),
    DirectionMode: require("./enum/DirectionMode.enum"),
}